#!/bin/bash

# chkconfig: 35 85 15
# description: Mongo is a scalable, document-oriented database.
# processname: mongod
# config: /etc/mongod.conf
# pidfile: /var/run/mongo/mongo.pid

#. /etc/rc.d/init.d/functions

MONGOHOME="/var/local/mongodb-linux-i686-2.4.1"
CONFIGFILE="/etc/mongod.conf"
DBPATH=`awk -F= '/^dbpath[ ]*=/{print $2}' "$CONFIGFILE" |sed -e 's/^[ ]*//'`
COMMAND="$MONGOHOME/bin/mongod"
OPT="--config $CONFIGFILE"
mongod=${MONGOD-$COMMAND}
PIDFILE=/var/run/mongodb.pid
LOCKFILE=/data/db/mongod.lock

usage() {
	echo "Usage: $0 {start|stop|restart|status}"
	exit 0
}

if [ $# != 1 ]; then
	usage
fi

start()
{
	status=$(status);
	if [ "${status}" == "MongoDB is running" ] ; then
		echo "MongoDB is already running";
		return 1;
	else
		if [ -e "${LOCKFILE}" ] ; then
			rm ${LOCKFILE};
		fi
	fi
	
	echo "Starting mongod"
	$COMMAND $OPT 2>&1 >> ${MONGOHOME}/mongo-start.log
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch ${PIDFILE}
}

stop()
{
	echo "Stopping mongod"
	kill $(cat "$DBPATH"/mongod.lock)
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f ${PIDFILE}
}

status() {
	running=$(ps -aef | grep -i mongod|grep -v grep|grep -v init.d|awk '{print $2}')
	if [ "${running}" != "" ] ; then
		echo "MongoDB is running"
		else
		echo "MongoDB is not running"
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		RETVAL=$?
		;;
	* )
		usage
		;;
esac
